[workspace]
members = [
  "crates/diag",
  "crates/emit",
  "crates/op",
  "crates/span",
  "crates/syntax",
  "crates/value",
]

# TODO: list shared dependencies here https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
# will make it easier to update

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
