[package]
name = "mu"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
portable = []

[dependencies]
diag = { path = "crates/diag", package = "mu_diag" }
span = { path = "crates/span", package = "mu_span" }
derive = { path = "crates/derive", package = "mu_derive" }
syntax = { path = "crates/syntax", package = "mu_syntax" }

beef = "0.5.2"
indexmap = "1.9.2"
paste = "1.0.11"


[dev-dependencies]
indoc = "1.0.8"
insta = "1.23.0"

rustyline = "10.1.0"
rustyline-derive = "0.7.0"
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive"] }

[workspace]
members = ["crates/*"]
resolver = "2"

# TODO: list shared dependencies here https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
# will make it easier to update

[profile.dev.package.insta]
opt-level = 3

[[example]]
name = "cli"
