[workspace]
members = [
  "crates/diag",
  "crates/emit",
  "crates/op",
  "crates/span",
  "crates/syntax",
  "crates/value",
]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
