[package]
name = "hebi"
version = "0.2.0"
edition = "2021"
description = "A dynamic scripting language"
repository = "https://github.com/jprochazk/hebi"
authors = ["jprochazk"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "cli"
# path = "bin/cli"

[features]
default = ["check_recursion_limit", "emit_snapshots"]
portable = []
check_recursion_limit = ["syntax/check_recursion_limit"]
emit_snapshots = []

[dependencies]
diag = { version = "0.2.0", path = "crates/diag", package = "hebi_diag" }
span = { version = "^0.0.1", path = "crates/span", package = "hebi_span" }
derive = { version = "0.2.0", path = "crates/derive", package = "hebi_derive" }
syntax = { version = "0.2.0", path = "crates/syntax", package = "hebi_syntax", default-features = false }

beef = { version = "0.5.2" }
indexmap = { version = "1.9.2" }
paste = { version = "1.0.11" }


[dev-dependencies]
indoc = { version = "1.0.8" }
insta = { version = "1.23.0" }

[workspace]
members = [
  "crates/derive", "crates/diag", "crates/span", "crates/syntax",
  "cli",
  "samples/*"
]
resolver = "2"

# TODO: list shared dependencies here https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
# will make it easier to update

[profile.dev.package.insta]
opt-level = 3
