[package]
name = "hebi"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/jprochazk/hebi"
authors = ["jprochazk"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["check-recursion-limit"]
portable = []
check-recursion-limit = ["syntax/check-recursion-limit"]

[dependencies]
diag = { path = "crates/diag", package = "hebi_diag" }
span = { path = "crates/span", package = "hebi_span" }
derive = { path = "crates/derive", package = "hebi_derive" }
syntax = { path = "crates/syntax", package = "hebi_syntax", default-features = false }

beef = "0.5.2"
indexmap = "1.9.2"
paste = "1.0.11"


[dev-dependencies]
indoc = "1.0.8"
insta = "1.23.0"

rustyline = "10.1.0"
rustyline-derive = "0.7.0"
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive"] }

[workspace]
members = ["crates/derive", "crates/diag", "crates/span", "crates/syntax"]
resolver = "2"

# TODO: list shared dependencies here https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
# will make it easier to update

[profile.dev.package.insta]
opt-level = 3

[[example]]
name = "cli"
