[package]
name = "mu_value"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
disable_snapshot_tests = []

[dependencies]

[dev-dependencies]
indoc = "1.0.8"
insta = "1.23.0"
