[package]
name = "mu_op"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beef = "0.5.2"
paste = "1.0.11"
static_assertions = "1.1.0"
op_macros = { path = "../op_macros", package = "mu_op_macros" }
