name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

# nightly version = nightly-2023-07-01

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, "nightly-2023-07-01"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Linting
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly-2023-07-01]
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: test
  miri:
    name: Miri
    runs-on: ubuntu-22.04
    env:
      TOOLCHAIN: "nightly-2023-07-01"
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          components: miri, rust-src

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run miri tests
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: miri test

